# Generated by Django 6.0.2 on 2026-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("code3", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("numeric", models.CharField(blank=True, max_length=3)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("numeric", models.CharField(blank=True, max_length=3)),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True, related_name="currencies", to="core.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True, related_name="languages", to="core.country"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("offset_seconds", models.IntegerField(default=0)),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True, related_name="timezones", to="core.country"
                    ),
                ),
            ],
            options={
                "ordering": ["offset_seconds", "name"],
            },
        ),
    ]
