# Generated by Django 6.0.2 on 2026-02-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Organisation logo (optional). Displayed in the app header.",
                null=True,
                upload_to="tenant_logos/",
                verbose_name="logo",
            ),
        ),
    ]
