# Generated by Django 6.0.2 on 2026-02-22 20:27
"""
Data migration: clear UserProfile.language for all existing rows.

After the Phase 4 locale restructure the project uses 'nl-be'/'fr-be' as the
Django LANGUAGES codes, and language preferences are now synced to the
django_language cookie on every profile save.  Any language FK values that
pre-date this change are stale (they were set from navigator.language without
being tied to a supported LANGUAGES code).  Clearing them forces users to
re-select a language in their profile — the UI locale will then be set
correctly via the cookie on the next save.
"""

from django.db import migrations


def clear_language(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.update(language=None)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(clear_language, migrations.RunPython.noop),
    ]
