# Generated by Django 6.0.2 on 2026-02-22 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_clear_userprofile_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="currency",
        ),
    ]
